### ISSUE TITLE
TypeError: container.init is not a function in Angular 13 and nrwl monorepo

### ISSUE THREAD

**Issue by piotrsikorski6** [angular-architects/module-federation-plugin#170]
I have tried everything, I guess. And I get the same error every time.

package.json
```
"dependencies": {
    "@angular-architects/module-federation": "^14.0.1",
    "@angular/animations": "13.1.2",
    "@angular/cdk": "13.1.2",
    "@angular/common": "13.1.2",
    "@angular/compiler": "13.1.2",
    "@angular/core": "13.1.2",
    "@angular/elements": "13.1.2",
    "@angular/forms": "13.1.2",
    "@angular/localize": "13.1.2",
    "@angular/platform-browser": "13.1.2",
    "@angular/platform-browser-dynamic": "13.1.2",
    "@angular/router": "13.1.2",
    "@nebular/bootstrap": "^9.0.0",
    "@nebular/eva-icons": "^9.0.0",
    "@nebular/theme": "^9.0.0",
    "@ng-bootstrap/ng-bootstrap": "^11.0.0",
    "@ngrx/component-store": "13.0.2",
    "@ngrx/effects": "13.0.2",
    "@ngrx/entity": "13.0.2",
    "@ngrx/router-store": "13.0.2",
    "@ngrx/store": "13.0.2",
    "bootstrap": "^5.1.3",
    "css-grid": "^1.0.7",
    "eva-icons": "^1.1.2",
    "file-saver": "^2.0.5",
    "js-cookie": "^3.0.1",
    "lodash": "^4.17.21",
    "ngx-build-plus": "^13.0.1",
    "ngx-spinner": "^12.0.0",
    "roboto-fontface": "^0.10.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "xlsx": "^0.18.3",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "13.1.3",
    "@angular-eslint/eslint-plugin": "13.0.1",
    "@angular-eslint/eslint-plugin-template": "13.0.1",
    "@angular-eslint/template-parser": "13.0.1",
    "@angular/cli": "13.1.3",
    "@angular/compiler-cli": "13.1.2",
    "@angular/language-service": "13.1.2",
    "@ngrx/schematics": "13.0.2",
    "@ngrx/store-devtools": "13.0.2",
    "@nrwl/angular": "13.4.4",
    "@nrwl/cli": "13.4.4",
    "@nrwl/cypress": "13.4.4",
    "@nrwl/eslint-plugin-nx": "13.4.4",
    "@nrwl/jest": "13.4.4",
    "@nrwl/linter": "13.4.4",
    "@nrwl/tao": "13.4.4",
    "@nrwl/workspace": "13.4.4",
    "@schematics/angular": "^12.2.11",
    "@types/jest": "27.0.2",
    "@types/js-cookie": "^3.0.1",
    "@types/lodash": "^4.14.178",
    "@types/node": "14.14.33",
    "@typescript-eslint/eslint-plugin": "5.3.1",
    "@typescript-eslint/parser": "5.3.1",
    "cypress": "^8.3.0",
    "eslint": "8.2.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jasmine-marbles": "~0.8.3",
    "jest": "27.2.3",
    "jest-preset-angular": "11.0.0",
    "prettier": "^2.3.1",
    "ts-jest": "27.0.5",
    "typescript": "4.5.4",
    "webpack": "^5.64.1"
  }
```
```
webpack.config of subproject (not shell):
module.exports = {
  experiments: {
    outputModule: true,
  },
  output: {
    uniqueName: 'sub-project',
    publicPath: 'auto',
    scriptType: 'text/javascript'
  },
  optimization: {
    runtimeChunk: false,
    minimize: false,
  },
  resolve: {
    alias: {
      ...sharedMappings.getAliases(),
    },
  },
  plugins: [
    new ModuleFederationPlugin({
      library: {
        type: 'module',
      },
      name: "sub-project",
      filename: "remoteEntry.js",
      exposes: {
        './web-components': './apps/sub-project/src/bootstrap.ts', // bootstrap --> main --> AppModule --> WebComp
      },
      remotes: {},
      shared: {
        '@angular/core': {
          singleton: true,
          strictVersion: true,
          requiredVersion: '13.1.2',
        },
        '@angular/common': {
          singleton: true,
          strictVersion: true,
          requiredVersion: '13.1.2',
        },
        '@angular/common/http': {
          singleton: true,
          strictVersion: true,
          requiredVersion: '13.1.2',
        },
        '@angular/router': {
          singleton: true,
          strictVersion: true,
          requiredVersion: '13.1.2',
        },
        ...sharedMappings.getDescriptors(),
      },
    }),
    sharedMappings.getPlugin(),
  ],
```
main.ts
`import('./bootstrap').catch((err) => console.error(err));`

bootstrap.ts
```
if (environment.production) {
  enableProdMode();
}

declare const require: any;
// eslint-disable-next-line @typescript-eslint/no-var-requires
const ngVersion = require('../../../package.json').dependencies['@angular/core'];
(window as any).plattform = (window as any).plattform || {};
let platform = (window as any).plattform[ngVersion];
if (!platform) {
  platform = platformBrowserDynamic();
  (window as any).plattform[ngVersion] = platform; 
}
platform.bootstrapModule(AppModule)
  .catch((err: any) => console.error(err));

```
project.json (aka angular.json)

```
{
  "projectType": "application",
  "root": "apps/sub-project",
  "sourceRoot": "apps/sub-project/src",
  "prefix": "frontend",
  "targets": {
    "build": {
      "builder": "ngx-build-plus:browser",
      "outputs": [
        "{options.outputPath}"
      ],
      "options": {
        "outputPath": "dist/apps/sub-project",
        "index": "apps/sub-project/src/index.html",
        "main": "apps/sub-project/src/main.ts",
        "polyfills": "apps/sub-project/src/polyfills.ts",
        "tsConfig": "apps/sub-project/tsconfig.app.json",
        "inlineStyleLanguage": "scss",
        "assets": [
          "apps/sub-project/src/favicon.ico",
          "apps/sub-project/src/assets"
        ],
        "styles": [
          "node_modules/bootstrap/dist/css/bootstrap.css",
          "node_modules/roboto-fontface/css/roboto/roboto-fontface.css",
          "node_modules/@nebular/theme/styles/prebuilt/default.css",
          "apps/sub-project/src/styles/styles.scss",
          "libs/shared/styles/styles.scss"
        ],
        "scripts": [],
        "extraWebpackConfig": "apps/sub-project/webpack.config.js"
      },
      "configurations": {
        "production": {
          "budgets": [
            {
              "type": "initial",
              "maximumWarning": "500kb",
              "maximumError": "1mb"
            },
            {
              "type": "anyComponentStyle",
              "maximumWarning": "4kb",
              "maximumError": "10kb"
            }
          ],
          "fileReplacements": [
            {
              "replace": "apps/sub-project/src/environments/environment.ts",
              "with": "apps/sub-project/src/environments/environment.prod.ts"
            }
          ],
          "outputHashing": "all",
            "extraWebpackConfig": "apps/sub-project/webpack.prod.config.js"
        },
        "development": {
          "buildOptimizer": false,
          "optimization": false,
          "vendorChunk": true,
          "extractLicenses": false,
          "sourceMap": true,
          "namedChunks": true
        }
      },
      "defaultConfiguration": "production"
    },
    "serve": {
      "builder": "ngx-build-plus:dev-server",
      "configurations": {
        "production": {
          "browserTarget": "sub-project:build:production",
          "extraWebpackConfig": "apps/sub-project/webpack.prod.config.js"
        },
        "development": {
          "browserTarget": "sub-project:build:development",
          "extraWebpackConfig": "apps/sub-project/webpack.config.js"
        }
      },
      "defaultConfiguration": "development",
      "options": {
        "port": 4203,
        "extraWebpackConfig": "apps/sub-project/webpack.config.js",
        "publicHost": "http://localhost:4203"
      }
    },
    "extract-i18n": {
      "executor": "ngx-build-plus:extract-i18n",
      "options": {
        "browserTarget": "sub-project:build"
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "options": {
        "lintFilePatterns": [
          "apps/sub-project/src/**/*.ts",
          "apps/sub-project/src/**/*.html"
        ]
      }
    },
    "test": {
      "executor": "ngx-build-plus:karma",
      "outputs": [
        "coverage/apps/sub-project"
      ],
      "options": {
        "jestConfig": "apps/sub-project/jest.config.js",
        "passWithNoTests": true
      }
    },
    "serve-mfe": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "nx serve sub-project"
        ]
      }
    }
  },
  "tags": []
}

```

**Comment by jdgeier** [comment]
in your webpack config make sure you are adding all your dependencies such as rxjs and rxjs/operators

**Comment by piotrsikorski6** [comment]
> 

Added to webpack.config.js of subproject:
```
     rxjs: {
          singleton: true,
          strictVersion: true,
          requiredVersion: '6.6.0',
        },
```
And got error:
```
ChunkLoadError: Loading chunk default-node_modules_rxjs__esm2015_internal_Observable_js failed.
(error: http://localhost:4207/default-node_modules_rxjs__esm2015_internal_Observable_js.js)
    at Object.__webpack_require__.f.j (jsonp chunk loading:27:1)
    at ensure chunk:6:1
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (ensure chunk:5:1)
    at Object../web-components (container-entry:3:1)
    at Module.get (container-entry:10:1)
    at angular-architects-module-federation-runtime.js:9:1
    at Generator.next (<anonymous>)
    at tslib.es6.js:76:1
    at new ZoneAwarePromise (zone.js:1387:1)
```

**Comment by AntoineGaugry** [comment]
Hi, I've got the same issue when using lazyLoading.

before => 
```ts
     loadChildren: () => loadRemoteModule({
      remoteEntry: 'http://localhost:4201/remoteEntry.js',
      remoteName: 'myRemote',
      exposedModule: './Module',
    }).then(m => m.RemoreModule)
```

I've changed the "remoteName" by Type: "Module"

after =>
```ts
  loadChildren: () => loadRemoteModule({
      remoteEntry: 'http://localhost:4201/remoteEntry.js',
      type: 'module',
      exposedModule: './Module',
    }).then(m => m.FederationDescriptionModule) 
```

It worked for me. 

Find the solution there [https://github.com/angular-architects/module-federation-plugin/issues/28](url).

Hope that will help you and others

**Comment by piotrsikorski6** [comment]
@AntoineGaugry Thank you.
I don't use lazy loading in this configuration:

```
const angularModules = [
  BrowserModule,
  RouterModule.forRoot([
    { path: '', component: HomeComponent, pathMatch: 'full' },
    { matcher: startsWith('sub-project'), component: WrapperComponent, data: { importName: 'sub-project', elementName: 'sub-project-element', type: 'module' }}
  ], { initialNavigation: 'enabledBlocking' }),
  HttpClientModule,
  BrowserAnimationsModule
];
```

Nx + mf configuration is a nightmare :)

**Comment by piotrsikorski6** [comment]
@manfredsteyer @Coly010 Could you please help with this issue? I know I'm close, but unfortunately, nothing helps.

**Comment by Dominik-Meier** [comment]
Any updated on this issue? As I'm stuck at the same point.

**Comment by piotrsikorski6** [comment]
@Dominik-Meier  What have you actually done? My version above is compatible with solution #96. But they still don't work

**Comment by piotrsikorski6** [comment]
This is a different case. I'm also using angular-elements.

**Comment by piotrsikorski6** [comment]
@jdgeier Thank you, will try, but what Do you mean by "include secondary entry points for libs too"?

**Comment by reggiepangilinan** [comment]
Any updates on this issue? I'm stuck with this error

```
core.mjs:6509 ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk src_app_remoteapp_module_ts failed.
(error: http://localhost:7000/src_app_remoteapp_module_ts.js)
ChunkLoadError: Loading chunk src_app_remoteapp_module_ts failed.
(error: http://localhost:7000/src_app_remoteapp_module_ts.js)
    at Object.__webpack_require__.f.j (remoteEntry.js:3541:28)
    at remoteEntry.js:3135:39
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (remoteEntry.js:3134:66)
    at Object../Module (remoteEntry.js:3039:30)
    at Module.get (remoteEntry.js:3046:23)
    at src_bootstrap_ts.js:205:41
    at Generator.next (<anonymous>)
    at node_modules_angular_router_fesm2020_router_mjs-_6f001.js:3001:71
    at new ZoneAwarePromise (polyfills.js:4524:29)
    at resolvePromise (polyfills.js:4308:31)
    at resolvePromise (polyfills.js:4262:17)
    at polyfills.js:4375:17
    at _ZoneDelegate.invokeTask (polyfills.js:3503:31)
    at Object.onInvokeTask (node_modules_angular_core_fesm2020_core_mjs.js:32497:25)
    at _ZoneDelegate.invokeTask (polyfills.js:3502:60)
    at Zone.runTask (polyfills.js:3275:47)
    at drainMicroTaskQueue (polyfills.js:3682:35)
    at ZoneTask.invokeTask [as invoke] (polyfills.js:3588:21)
    at invokeTask (polyfills.js:4745:18)
```

I'm using Angular 13 and Module fedaration 14 in both my host and shell

Here is my config

🏠 **HOST**

Loading modules in my routes
```
{
  path: 'mfe1',
  loadChildren: () => loadRemoteModule({
      remoteEntry: 'http://localhost:3100/remoteEntry.js',
      type: 'module',
      exposedModule: './Module'
    })
    .then(m => m.RemoteAppModule) 
},
```
webpack.config,js
```
module.exports = {
  output: {
    uniqueName: "shell",
    publicPath: "auto",
    scriptType: 'text/javascript'
  },
  optimization: {
    runtimeChunk: false
  },   
  resolve: {
    alias: {
      ...sharedMappings.getAliases(),
    }
  },
  experiments: {
    outputModule: true
  },
  plugins: [
    new ModuleFederationPlugin({
        library: { type: "module" },
        shared: share({
          "@angular/core": { singleton: true, strictVersion: true, requiredVersion: 'auto' }, 
          "@angular/common": { singleton: true, strictVersion: true, requiredVersion: 'auto' }, 
          "@angular/common/http": { singleton: true, strictVersion: true, requiredVersion: 'auto' }, 
          "@angular/router": { singleton: true, strictVersion: true, requiredVersion: 'auto' },

          ...sharedMappings.getDescriptors()
        })
        
    }),
    sharedMappings.getPlugin()
  ],
};

```

🌐 **REMOTE**

webpack.config.js

```
module.exports = {
  output: {
    uniqueName: "mfe1",
    publicPath: "auto",
    scriptType: 'text/javascript'
  },
  optimization: {
    runtimeChunk: false,
    splitChunks: {
      chunks: 'async'
    }

  },   
  resolve: {
    alias: {
      ...sharedMappings.getAliases(),
    }
  },
  experiments: {
    outputModule: true
  },
  plugins: [
    new ModuleFederationPlugin({
        library: { type: "module" },

        // For remotes (please adjust)
        name: "mfe1",
        filename: "remoteEntry.js",
        exposes: {
            "./Module": './src/app/remoteapp.module.ts',
        },        
        shared: share({
          "@angular/core": { singleton: true, strictVersion: true, requiredVersion: 'auto' }, 
          "@angular/common": { singleton: true, strictVersion: true, requiredVersion: 'auto' }, 
          "@angular/common/http": { singleton: true, strictVersion: true, requiredVersion: 'auto' }, 
          "@angular/router": { singleton: true, strictVersion: true, requiredVersion: 'auto' },

          ...sharedMappings.getDescriptors()
        })
        
    }),
    sharedMappings.getPlugin()
  ],
};
```

**Comment by piotrsikorski6** [comment]
Nothing has changed, I am still waiting for any help @manfredsteyer @Coly010 .

@reggiepangilinan Could you please create your own ticket? This is a different setup/approach and it causes chaos.

**Comment by Coly010** [comment]
@piotrsikorski6 looking over this, there isn't enough information to investigate. Secondly, you keep tagging me, and while I'd like to help, I'm not 100% sure why? This is not the Nx Module Federation support.

**Comment by piotrsikorski6** [comment]
Sorry, you're a top expert and to tell you the truth - I try everything. That is why I allowed myself to write so directly.
I do everything based on the available information and just give up hope about how to use monorepo with module federation and microfrontend. Can I attach sth more information?
