### ISSUE TITLE
The "to" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by ProfEibe** [angular-architects/module-federation-plugin#175]
I always get the following error while trying to initialize the plugin in an nx project.
I first install the plugin: `npm install @angular-architects/module-federation`
Then I want to start the init function with: `nx g @angular-architects/module-federation:init`

I use nx instead of ng because of the splitted angular.json file.
But after entering the project-name and the port I get the following error message:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.relative (path.js:493:5)
    at generateSsrMappings (C:\Users\Schade\IdeaProjects\camunda\node_modules\@angular-architects\module-federation\src\schematics\mf\schematic.js:285:37)
    at C:\Users\Schade\IdeaProjects\camunda\node_modules\@angular-architects\module-federation\src\schematics\mf\schematic.js:217:33
    at Generator.next (<anonymous>)
    at C:\Users\Schade\IdeaProjects\camunda\node_modules\@angular-architects\module-federation\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Schade\IdeaProjects\camunda\node_modules\@angular-architects\module-federation\node_modules\tslib\tslib.js:111:16)
    at C:\Users\Schade\IdeaProjects\camunda\node_modules\@angular-architects\module-federation\src\schematics\mf\schematic.js:132:24
    at MergeMapSubscriber.project (C:\Users\Schade\IdeaProjects\camunda\node_modules\@angular-devkit\schematics\src\rules\call.js:75:24) {
  code: 'ERR_INVALID_ARG_TYPE'
}
The "to" argument must be of type string. Received undefined
```

What can I do to prevent this? My wish is to make one of my apps in my nx-workspace accessable for an other angular application outside of this workspace. I was hoping to use module federation for this.

**Comment by frontendplace** [comment]
same here

**Comment by hugomenz** [comment]
Hello, I've encountered the same issue while trying to use the @angular-architects/module-federation plugin in my Nx project. I also received the "to" argument error when running the nx g @angular-architects/module-federation:init command.

I found that the error originates from the generateSsrMappings function in the schematic.js file. The path.relative() function expects both "from" and "to" arguments to be of type string, but it seems that the "to" argument can sometimes be undefined, causing the error.

A temporary workaround could involve modifying the schematic.js file to add a fallback value for the "to" argument. 

```javascript
// changed this line
const relOutPath = path.relative(projectOutPath, outPath).replace(/\\/g, '/') + '/';

// to 
const relOutPath = path.relative(projectOutPath, outPath || '').replace(/\\/g, '/') + '/';
```

However, this is not an ideal solution, as it requires manual changes to the package's source code...

Here are my project's dependencies for reference:

```json
"dependencies": {
    "@angular-architects/module-federation": "^15.0.3",
    "@angular/animations": "~15.2.0",
    "@angular/common": "~15.2.0",
    "@angular/compiler": "~15.2.0",
    "@angular/core": "~15.2.0",
    "@angular/forms": "~15.2.0",
    "@angular/platform-browser": "~15.2.0",
    "@angular/platform-browser-dynamic": "~15.2.0",
    "@angular/router": "~15.2.0",
    "@nrwl/angular": "15.9.2",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~15.2.0",
    "@angular-devkit/core": "~15.2.0",
    "@angular-devkit/schematics": "~15.2.0",
    "@angular-eslint/eslint-plugin": "~15.0.0",
    "@angular-eslint/eslint-plugin-template": "~15.0.0",
    "@angular-eslint/template-parser": "~15.0.0",
    "@angular/cli": "~15.2.0",
    "@angular/compiler-cli": "~15.2.0",
    "@angular/language-service": "~15.2.0",
    "@nrwl/cypress": "15.9.2",
    "@nrwl/esbuild": "15.9.2",
    "@nrwl/eslint-plugin-nx": "15.9.2",
    "@nrwl/jest": "15.9.2",
    "@nrwl/js": "^15.9.2",
    "@nrwl/linter": "15.9.2",
    "@nrwl/node": "15.9.2",
    "@nrwl/web": "15.9.2",
    "@nrwl/workspace": "15.9.2",
    "@schematics/angular": "~15.2.0",
    "@types/jest": "^29.4.0",
    "@types/node": "~18.7.1",
    "@typescript-eslint/eslint-plugin": "^5.36.1",
    "@typescript-eslint/parser": "^5.36.1",
    "cypress": "^12.2.0",
    "esbuild": "^0.17.5",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "^29.4.1",
    "jest-environment-jsdom": "^29.4.1",
    "jest-preset-angular": "~13.0.0",
    "ngx-build-plus": "^15.0.0",
    "nx": "15.9.2",
    "prettier": "^2.6.2",
    "ts-jest": "^29.0.5",
    "ts-node": "10.9.1",
    "typescript": "~4.9.5"
  }
```

Please let me know if there's any more information I can provide or if there's a recommended solution to this issue. I'm looking forward to using module federation in my project. Thank you!

**Comment by hugomenz** [comment]
I've encountered the same issue while trying to use the @angular-architects/module-federation plugin in my Nx project. I also received the "to" argument error when running the nx g @angular-architects/module-federation:init command.

I found that the error originates from the generateSsrMappings function in the schematic.js file. The path.relative() function expects both "from" and "to" arguments to be of type string, but it seems that the "to" argument can sometimes be undefined, causing the error.

A temporary workaround could involve modifying the schematic.js file to add a fallback value for the "to" argument. 

```javascript
// changed this line
const relOutPath = path.relative(projectOutPath, outPath).replace(/\\/g, '/') + '/';

// to 
const relOutPath = path.relative(projectOutPath, outPath || '').replace(/\\/g, '/') + '/';
```

However, this is not an ideal solution, as it requires manual changes to the package's source code...

Here are my project's dependencies for reference:

```json
"dependencies": {
    "@angular-architects/module-federation": "^15.0.3",
    "@angular/animations": "~15.2.0",
    "@angular/common": "~15.2.0",
    "@angular/compiler": "~15.2.0",
    "@angular/core": "~15.2.0",
    "@angular/forms": "~15.2.0",
    "@angular/platform-browser": "~15.2.0",
    "@angular/platform-browser-dynamic": "~15.2.0",
    "@angular/router": "~15.2.0",
    "@nrwl/angular": "15.9.2",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~15.2.0",
    "@angular-devkit/core": "~15.2.0",
    "@angular-devkit/schematics": "~15.2.0",
    "@angular-eslint/eslint-plugin": "~15.0.0",
    "@angular-eslint/eslint-plugin-template": "~15.0.0",
    "@angular-eslint/template-parser": "~15.0.0",
    "@angular/cli": "~15.2.0",
    "@angular/compiler-cli": "~15.2.0",
    "@angular/language-service": "~15.2.0",
    "@nrwl/cypress": "15.9.2",
    "@nrwl/esbuild": "15.9.2",
    "@nrwl/eslint-plugin-nx": "15.9.2",
    "@nrwl/jest": "15.9.2",
    "@nrwl/js": "^15.9.2",
    "@nrwl/linter": "15.9.2",
    "@nrwl/node": "15.9.2",
    "@nrwl/web": "15.9.2",
    "@nrwl/workspace": "15.9.2",
    "@schematics/angular": "~15.2.0",
    "@types/jest": "^29.4.0",
    "@types/node": "~18.7.1",
    "@typescript-eslint/eslint-plugin": "^5.36.1",
    "@typescript-eslint/parser": "^5.36.1",
    "cypress": "^12.2.0",
    "esbuild": "^0.17.5",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "^29.4.1",
    "jest-environment-jsdom": "^29.4.1",
    "jest-preset-angular": "~13.0.0",
    "ngx-build-plus": "^15.0.0",
    "nx": "15.9.2",
    "prettier": "^2.6.2",
    "ts-jest": "^29.0.5",
    "ts-node": "10.9.1",
    "typescript": "~4.9.5"
  }
```

Please let me know if there's any more information I can provide or if there's a recommended solution to this issue. I'm looking forward to using module federation in my project.

**Comment by MaGnaL** [comment]
Had the same problem. I think `@angular-architects/module-federation:init` is trying to create the remote entries for all existing application in the monorepo. Therefore it looks for the option "outputPath" in the "build" target of each app. The error occurs, if an app doesn't have this option configured in its "project.json".

Just add the option to make it run through. Of course you have to check the generated code in "assets/mf.manifest.json" of your app but you might end up adapting this file anyway.
