### ISSUE TITLE
"includeSecondaries" options leads to validation errors in ModuleFederationPlugin

### ISSUE THREAD

**Issue by MadeleineCodes** [angular-architects/module-federation-plugin#192]
Hi! I am currently working on updating our nx repository to Angular 14. During that I also updated module-federation-plugin to 14.3.0 which (among other things) brought the change that `includeSecondaries` is `true` by default. As this does not work for some of our local packages, I tried to set it explicitly to `false`. However, this resulted in the following error:

```
- Generating browser application bundles (phase: setup)...Invalid options object. Module Federation Plugin has been initialized using an options object that does not match the API schema.
 - options.shared['@org/internal-components'] has an unknown property 'includeSecondaries'. These properties are valid:
   object { eager?, import?, packageName?, requiredVersion?, shareKey?, shareScope?, singleton?, strictVersion?, version? }
   -> Advanced configuration for modules that should be shared in the share scope.
ValidationError: Invalid options object. Module Federation Plugin has been initialized using an options object that does not match the API schema.
 - options.shared['@org/internal-components'] has an unknown property 'includeSecondaries'. These properties are valid:
   object { eager?, import?, packageName?, requiredVersion?, shareKey?, shareScope?, singleton?, strictVersion?, version? }
   -> Advanced configuration for modules that should be shared in the share scope.
    at validate (~\node_modules\schema-utils\dist\validate.js:105:11)
    at ~\node_modules\webpack\lib\util\create-schema-validation.js:16:17
    at new ModuleFederationPlugin (~\node_modules\webpack\lib\container\ModuleFederationPlugin.js:32:3)
    at Object.<anonymous> (~\apps\my-app\extra-webpack.config.js:181:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

I noticed that the `share` helper only deletes `includeSecondaries` only if it is `true` (see #233): https://github.com/angular-architects/module-federation-plugin/blob/5b1ac420ee51afb065ec0f3c2450ac54311e24f7/libs/mf/src/utils/share-utils.ts#L205-L246 
So in my case, it's not removed and therefore leads to the above validation error.
If I move the deletion out of the `if`, so that it happens in any case, it works fine.

Is this intentional? Did I miss something else in the configuration that has to be considered? If this is indeed a bug I am willing to provide a PR with a fix, just let me know. :)

Thanks a lot!

------

Version information:

+-- @angular-architects/module-federation@14.3.8
+-- @angular-builders/custom-webpack@14.0.0
+-- @angular-devkit/architect@0.1400.2
+-- @angular-devkit/build-angular@14.0.2
+-- @angular-devkit/core@14.0.2
+-- @angular-devkit/schematics@14.0.2
+-- @angular/animations@14.0.2
+-- @angular/cdk@14.0.2
+-- @angular/cli@14.0.2
+-- @angular/common@14.0.2
+-- @angular/compiler-cli@14.0.2
+-- @angular/compiler@14.0.2
+-- @angular/core@14.0.2
+-- @angular/elements@14.0.2
+-- @angular/forms@14.0.2
+-- @angular/language-service@14.0.2
+-- @angular/material@14.0.2
+-- @angular/platform-browser-dynamic@14.0.2
+-- @angular/platform-browser@14.0.2
+-- @angular/router@14.0.2
+-- @ngrx/component-store@13.2.0
+-- @ngrx/effects@13.2.0
+-- @ngrx/store-devtools@13.2.0
+-- @ngrx/store@13.2.0
+-- @ngx-translate/core@13.0.0
+-- @nrwl/angular@14.3.6
+-- @nrwl/js@14.3.6
+-- @nrwl/node@14.3.6
+-- @types/jest@27.4.1
+-- @types/node@14.14.33
+-- @types/webpack@5.28.0
+-- core-js@3.21.0
+-- eslint@7.22.0
+-- jest-junit@12.0.0
+-- jest-localstorage-mock@2.4.21
+-- jest-preset-angular@11.1.2
+-- jest@27.5.1
+-- jstimezonedetect@1.0.7
+-- ng-packagr@14.0.2
+-- ngx-build-plus@14.0.0
+-- node-polyfill-webpack-plugin@1.1.4
+-- nx@14.3.6
+-- postcss-import@14.1.0
+-- postcss-preset-env@6.7.1
+-- postcss-url@10.1.3
+-- postcss@8.4.14
+-- prettier@2.5.1
+-- rxjs@7.5.5
+-- ts-jest@27.1.4
+-- ts-node@8.10.2
+-- tslib@2.4.0
+-- typescript@4.7.2
+-- webpack@5.72.0
`-- zone.js@0.11.5

**Comment by ssams** [comment]
just ran into the same issue, does a PR already exist for this? can confirm that the suggested fix of moving the `delete` out of the condition works as expected, tested with a locally patched version.

**Comment by MadeleineCodes** [comment]
Just created #206 :)
