### ISSUE TITLE
mf-tools:V14:web-components:Cannot match any routes. URL Segment: 'angular14'

### ISSUE THREAD

**Issue by CP-Ram** [angular-architects/module-federation-plugin#209]
I am using angular v14.1.1 and ```"@angular-architects/module-federation": "^14.3.10","@angular-architects/module-federation-tools": "^14.3.10"```.And exposes web-components from remote app.
shell app routes:
```
const routes: Routes = [ 
{
  path: 'angular14',
  component: WebComponentWrapper,
  data: {
    type:'module',
    remoteEntry: 'http://localhost:4201/remoteEntry.js',
    exposedModule: './web-components',
    elementName: 'angular14-customer'
  } as WebComponentWrapperOptions
}
];
```
remote app webpack.config:
```
module.exports = withModuleFederationPlugin({
  name: "angular14",
  // library: { type: "module", name: "angular14" },
  filename: "remoteEntry.js",
  exposes: {
    './web-components': './src/bootstrap.ts',
  },

  shared: {
    ...shareAll({ singleton: true, strictVersion: true, requiredVersion: 'auto' }),
  },

});
```
remote module angular elements:
```
export class AppModule implements DoBootstrap
{
  constructor(private injector: Injector) { }
  ngDoBootstrap(): void {
    if (!customElements.get('angular14-customer')) {
      customElements.define(
        'angular14-customer',
        createCustomElement(MFEComponent, { injector: this.injector })
      );
    }
  }
 }
```

Sample angular v14  application work fine with other routes but once try to access MF web-components routes path in shell app getting error.

Error:
core.mjs:7644 ERROR Error: Uncaught (in promise): Error: NG04002: Cannot match any routes. URL Segment: 'angular14'
Error: NG04002: Cannot match any routes. URL Segment: 'angular14'
    at ApplyRedirects.noMatchError (router.mjs:3578:16)
    at router.mjs:3560:28
    at catchError.js:10:39
    at OperatorSubscriber._error (OperatorSubscriber.js:23:21)
    at OperatorSubscriber.error (Subscriber.js:40:18)
    at OperatorSubscriber._error (Subscriber.js:64:30)
    at OperatorSubscriber.error (Subscriber.js:40:18)
    at OperatorSubscriber._error (Subscriber.js:64:30)
    at OperatorSubscriber.error (Subscriber.js:40:18)
    at OperatorSubscriber._error (Subscriber.js:64:30)
    at resolvePromise (zone.js:1211:31)
    at resolvePromise (zone.js:1165:17)
    at zone.js:1278:17
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26367:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)

**Comment by pdashford** [comment]
I to am experiencing the same issues.

```
const routes: Routes = [
  {
    path: '',
    component: HomeComponent,
    pathMatch: 'full',
  },
  {
    matcher: startsWith('angular1'),
    component: WebComponentWrapper,
    data: {
      type: 'module',
      remoteEntry: 'http://localhost:4205/remoteEntry.js',
      exposedModule: './web-components',

      elementName: 'angular1-element',
    } as WebComponentWrapperOptions,
  },
];
```

In the shell app if I routerlink to `angular1` I receive the following error.

```
rror: Uncaught (in promise): Error: NG04002: Cannot match any routes. URL Segment: 'angular1'
Error: NG04002: Cannot match any routes. URL Segment: 'angular1'
```

However if I use the `mft-wc-wrapper` the routes then appears to work 

```
<mft-wc-wrapper [options]="item"></mft-wc-wrapper>

export class HomeComponent {
  title = 'shell';
  item: WebComponentWrapperOptions = {
    remoteEntry: 'http://localhost:4205/remoteEntry.js',
    exposedModule: './web-components',
    elementName: 'angular1-element',
    type: 'module',
  };
}
```

**Comment by CP-Ram** [comment]
@pdashford - quite not understand. 
could you please explain,As we don't have router module in MFEs, even though getting above error.

 -If MFEs doesn't have router module and path, just exposing web components, using shell app router to navigateByUrl to Mfes web component. 
what is the resolution for the above error?
