### ISSUE TITLE
Error: Cannot enable prod mode after platform setup

### ISSUE THREAD

**Issue by CP-Ram** [angular-architects/module-federation-plugin#225]
Error: Cannot enable prod mode after platform setup.
**package detail:**
```
    "@angular-architects/module-federation": "14.3.10",
    "@angular-architects/module-federation-tools": "14.3.10",    
    "@angular/common": "14.2.0",
    "@angular/compiler": "14.2.0",
    "@angular/core": "14.2.0"
```

**Current Behavior:** when we load two or more remote apps throw error ```Cannot enable prod mode after platform setup```.

**Apps details:**
   1.shell app
   2.mfe1
   3. mfe2
   
**Steps to reproduce:**
1. build all apps with configuration = production
2. load mfe1
3. load mfe2 and nothing will load and throw error ``` Cannot enable prod mode after platform setup```.

**Environment:**
production build

**Error:**
```
Error: Cannot enable prod mode after platform setup.
    at wM (7464.js:1:182913)
    at 3140 (140.js:1:1696513)
    at e (mf2.js:1:572)
    at mf2.js:1:80
    at 245.js:1:7329
    at p (245.js:1:1563)
    at d._invoke (245.js:1:1323)
    at Generator.next (245.js:1:1923)
    at u (245.js:1:6876)
    at d.invoke (polyfills.js:1:7312)
```

**Comment by scottwalter-nice** [comment]
How are you bootstrapping your mfe app?

**Comment by r1m** [comment]
I'm facing the same issue with webcomponents. It is because the bootstrapComponent method is setting the production mode even if the platform is shared 
https://github.com/angular-architects/module-federation-plugin/blob/14.2.0/libs/mf-tools/src/lib/web-components/bootstrap-utils.ts#L162

This was fixed in 15.0.0 (only done during platform creation) but I see no backport of that fix. 😢

**Comment by r1m** [comment]
In my case it appears only when MFEs and shell are sharing the same angular version. The only workaround I found for now is to remove the production mode from MFEs or shell or both.

**Comment by r1m** [comment]
@manfredsteyer I wanted to submit a PR for this on 14.2.3 version. However I cannot find the related commit/tag nor a target branch for it. Could you help me on that ?
