### ISSUE TITLE
pipe not work 

### ISSUE THREAD

**Issue by alirezabahary** [angular-architects/module-federation-plugin#232]
my shell project version is 13 and remote project version is 14 .
pipe work in my remote project but when call remote project in my shell , I get an error:

core.mjs:6476 ERROR Error: Uncaught (in promise): Error: NG0302: The pipe 'date' could not be found in the 'RemoteComponent' component!. Find more at https://angular.io/errors/NG0302
Error: NG0302: The pipe 'date' could not be found in the 'RemoteComponent' component!. Find more at https://angular.io/errors/NG0302
    at getPipeDef (core.mjs:22291:15)
    at Module.ɵɵpipe (core.mjs:22243:19)
    at RemoteComponent_Template (remote.component.html:3:1)
    at executeTemplate (core.mjs:9608:9)
    at renderView (core.mjs:9411:13)
    at renderComponent$1 (core.mjs:10692:5)
    at renderChildComponents (core.mjs:9276:9)
    at renderView (core.mjs:9436:13)
    at ComponentFactory.create (core.mjs:21588:13)
    at ViewContainerRef.createComponent (core.mjs:22832:47)
    at resolvePromise (zone.js:1213:1)
    at resolvePromise (zone.js:1167:1)
    at zone.js:1279:1
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25470:33)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:582:1)
[card-board-micro-front-end.zip](https://github.com/angular-architects/module-federation-plugin/files/9638310/card-board-micro-front-end.zip)
[shell.zip](https://github.com/angular-architects/module-federation-plugin/files/9638311/shell.zip)

**Comment by manfredsteyer** [comment]
There are no guarantees that you can mix and match different angular versions.

**Comment by manfredsteyer** [comment]
If you need to load micro frontends built with several angular versions you could use this approach: https://www.npmjs.com/package/@angular-architects/module-federation-tools

**Comment by alirezabahary** [comment]
> If you need to load micro frontends built with several angular versions you could use this approach: https://www.npmjs.com/package/@angular-architects/module-federation-tools

tnx

**Comment by spierala** [comment]
I have a similar issue: 

Shell is using ng14, remote is using ng13.

This is the error: 
`ERROR Error: Uncaught (in promise): Error: NG0302: The pipe 'async' could not be found in the 'FlightsSearchComponent' component!`

![image](https://user-images.githubusercontent.com/1272446/215501924-24e44c58-fadb-4d5c-ad65-4d54913f0bfa.png)

In another setup I tried ng14 shell with ng12 remote... same error.

**Comment by huajian123** [comment]
@spierala How did you finally solve this problem?

**Comment by huajian123** [comment]
@alirezabahary Did you finally use webcomponent to solve this problem?
