### ISSUE TITLE
Angular 14 migration: loading issues with zone.js

### ISSUE THREAD

**Issue by csutorasr** [angular-architects/module-federation-plugin#234]
I tried to migrate to Angular 14.

Initially I had problems with webpack. It did not found the `exposes` modules. Updating webpack to the latest (`5.74.0` at the time of the writing) resolved the issue.

The errors were:

* `cannot find module '@angular/platform-browser'`
* `cannot find module 'exposed module'`

After upgrading the webpack version I get the following errors that I can not resolve:

## Without MFE:

When I try to run the application without MFE just using the `index.html`:

```
Uncaught Error: Shared module is not available for eager consumption: 10627
    at __webpack_require__.m.<computed> (consumes:428:1)
    at __webpack_require__ (bootstrap:19:1)
    at 62517 (polyfills.js:10:65)
    at __webpack_require__ (bootstrap:19:1)
    at startup:5:1
```

The `10627` module is the zone.js.

```
Uncaught SyntaxError: Cannot use 'import.meta' outside a module (at styles.js:8267:29)
```

```
Error: NG0908: In this configuration Angular requires Zone.js
    at new NgZone (core.mjs:26033:19)
    at getNgZone (core.mjs:27032:75)
    at PlatformRef.bootstrapModuleFactory (core.mjs:26899:24)
    at core.mjs:26955:41
```

## With MFE:

```
Uncaught Error: Uncaught (in promise): Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `EnvironmentInjector#runInContext`. Find more at https://angular.io/errors/NG0203
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `EnvironmentInjector#runInContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (core.mjs:4775:15)
    at Module.ɵɵinject (core.mjs:4786:12)
    at Object.StoreFeatureModule_Factory [as useFactory] (ngrx-store.mjs:1407:20)
    at Object.factory (core.mjs:6974:38)
    at R3Injector.hydrate (core.mjs:6887:35)
    at R3Injector.get (core.mjs:6775:33)
    at injectInjectorOnly (core.mjs:4782:33)
    at ɵɵinject (core.mjs:4786:12)
    at useValue (core.mjs:6567:65)
    at R3Injector.resolveInjectorInitializers (core.mjs:6824:17)
    at resolvePromise (zone.js:1213:31)
    at resolvePromise (zone.js:1167:17)
    at zone.js:1279:17
    at ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26218:33)
    at ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:582:35)
```

I use ngrx store here.

### Host:

```javascript
module.exports = withModuleFederationPlugin({
  shared: {
    ...shareAll({
      singleton: true,
      strictVersion: true,
      requiredVersion: 'auto',
    }),
  },
});
```

### MFE:

```javascript
module.exports = withModuleFederationPlugin({
  name: 'progress',
  filename: 'progressRemoteEntry.js',
  exposes: {
    './Module': 'apps/asd/src/app/remote-entry/entry.module.ts',
  },
  shared: {
    ...shareAll(
      {
        singleton: true,
        strictVersion: true,
        requiredVersion: 'auto',
      },
      ['rxjs']
    ),
    rxjs: {
      singleton: true,
      strictVersion: true,
      requiredVersion: '*',
    },
  },
});
```

I use imports like: `import { filter } from 'rxjs';` instead of `rxjs/operators` that's why I excluded it.

If you need any more info, please let me know. I tried my best with debugging into webpack. Tell me if you have any other ideas.

**Comment by csutorasr** [comment]
I forgot to add that without the custom webpack config the application compiles and runs.

**Comment by csutorasr** [comment]
I get the same errors for legacy Version 12 configuration with 'text/javascipt' without ES modules.

**Comment by csutorasr** [comment]
Finally I used the share function from NX. It has limitation like filename etc. But it works.
