### ISSUE TITLE
The Angular Webpack loader requires the AngularWebpackPlugin.

### ISSUE THREAD

**Issue by ronaldohoch** [angular-architects/module-federation-plugin#29]
Hello!

I have 2 questions:

# 1º
After read the section: Sharing Libs of a Monorepo, i put my lib in the webpack configuration file, see:

```javascript
const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const mf = require("@angular-architects/module-federation/webpack");
const path = require("path");

const sharedMappings = new mf.SharedMappings();
sharedMappings.register(
  path.join(__dirname, '../../tsconfig.base.json'),[
    "@dinamize/ui"
  ]);

module.exports = {
  output: {
    uniqueName: "appShell"
  },
  optimization: {
    runtimeChunk: false
  },
  plugins: [
    new ModuleFederationPlugin({
        remotes: {
          "emktConfig": "emktConfig@http://localhost:4201/remoteEntry.js"
        },
        shared: {
          "@angular/core": { singleton: true, strictVersion: true }, 
          "@angular/common": { singleton: true, strictVersion: true }, 
          "@angular/router": { singleton: true, strictVersion: true },
          "rxjs":{singleton:true, strictVersion: true},
          "rxjs/operators":{singleton:true, strictVersion: true},
          "rxjs/Observable":{singleton:true, strictVersion: true},
          ...sharedMappings.getDescriptors()
        }        
    }),
    sharedMappings.getPlugin(),
  ],
};
```

This throw me this error:
```
./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)
./libs/ui/src/lib/web/style/theme.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)
    at processResult (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\lib\NormalModule.js:576:19)
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\lib\NormalModule.js:669:5
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:9)
```

<details>
  <summary>The complete error log:</summary>
  
```shell
PS C:\Users\ronal\Documents\projetos\dinamize\MFE> ng serve app-shell
Your global Angular CLI version (11.2.8) is greater than your local version (11.0.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

> nx run app-shell:serve
⠋ Generating browser application bundles (phase: building)...(node:8140) [DEP_WEBPACK_CHUNK_INTEGRATE] DeprecationWarning: Chunk.integrate: Use new ChunkGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
⠧ Generating browser application bundles (phase: sealing)...
Initial Chunk Files                                                                                     | Names     |    Size
main.js                                                                                                 | main      | 0 bytes
polyfills.js                                                                                            | polyfills | 0 bytes
styles.js                                                                                               | styles    | 0 bytes

Lazy Chunk Files                                                                                        | Names     |    Size
apps_app-shell_src_bootstrap_ts.js                                                                      | -         | 0 bytes
default-libs_ui_src_index_ts.js                                                                         | -         | 0 bytes
default-node_modules_angular_common_fesm2015_common_js.js                                               | -         | 0 bytes
default-node_modules_rxjs__esm2015_internal_AsyncSubject_js-node_modules_rxjs__esm2015_intern-0da67e.js | -         | 0 bytes
node_modules_angular_core_fesm2015_core_js.js                                                           | -         | 0 bytes
node_modules_angular_router_fesm2015_router_js.js                                                       | -         | 0 bytes
node_modules_rxjs__esm2015_index_js.js                                                                  | -         | 0 bytes
node_modules_rxjs__esm2015_operators_index_js.js                                                        | -         | 0 bytes

4 unchanged chunks

Build at: 2021-04-14T16:45:11.970Z - Hash: 89d2f6e83e048eb513e9 - Time: 11698ms

./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)

./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)

./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)

./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)

./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)

./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)

./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)

./apps/app-shell/src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)
    at processResult (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\lib\NormalModule.js:576:19)
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\lib\NormalModule.js:669:5
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:9)

./libs/ui/src/lib/web/style/theme.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)
    at processResult (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\lib\NormalModule.js:576:19)
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\lib\NormalModule.js:669:5
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:9)



** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

✔ Browser application bundle generation complete.
(node:8140) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_INDEXER] DeprecationWarning: chunk.files was changed from Array to Set (indexing Array is deprecated)
⠸ Generating browser application bundles (phase: sealing)...
15 unchanged chunks

Build at: 2021-04-14T16:45:14.827Z - Hash: 89d2f6e83e048eb513e9 - Time: 2119ms

./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)

./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)

./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)

./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)

./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)

./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)

./libs/ui/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)

./apps/app-shell/src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)
    at processResult (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\lib\NormalModule.js:576:19)
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\lib\NormalModule.js:669:5
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:9)

./libs/ui/src/lib/web/style/theme.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:18)
    at processResult (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\lib\NormalModule.js:576:19)
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\lib\NormalModule.js:669:5
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.angularWebpackLoader (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\@ngtools\webpack\src\ivy\loader.js:28:9)


✔ Browser application bundle generation complete.
```
</details>

# 2º
What is the best way to change the remote url to test and production url
```
remotes: {
  "emktConfig": "emktConfig@http://localhost:4201/remoteEntry.js"
}
```

**Comment by kumaravnish** [comment]
+1

**Comment by smasala** [comment]
Same issue regarding `Sharing Libs of a Monorepo`

**Comment by smasala** [comment]
@ronaldohoch @manfredsteyer issue 1 mentioned above is linked to `stylesUrl` bug 😞 
The error occurs on the https://github.com/angular/angular-cli/blob/v11.2.2/packages/ngtools/webpack/src/ivy/loader.ts#L23 when trying to load styles

> Bug with styleUrls
Currently, there is, unfortunately, a bug in the experimental CLI/webpack5 integration causing issues when using shared libraries together with components pointing to styleUrls. For the time being, you can work around this issue by removing all styleUrls in your applications and libraries.
https://github.com/angular-architects/module-federation-plugin/blob/main/packages/mf/README.md#bug-with-styleurls

**Comment by glebmachine** [comment]
Jesus, i'm strugling about that so much!

Does anybody found workaround?
Looks like angular-cli authors doesn't give a toss. They block all issues about

![image](https://user-images.githubusercontent.com/1610882/115266886-43f4e080-a141-11eb-8109-d07170e525f6.png)

**Comment by smasala** [comment]
@ronaldohoch @glebmachine looks like the way to get this to work is **_not_** to use the `sharedMappings` section of this plugin.

In your webconfig add the shared lib the same way the angular deps are listed and with the same name as it is registered in the `tsconfig.json` paths.

```
shared: {
        '@angular/core': { singleton: true, strictVersion: true },
        '@angular/common': { singleton: true, strictVersion: true },
        '@angular/router': { singleton: true, strictVersion: true },
        "@myMonoRepNamespace/mySharedLib": {singleton: true},

        ...sharedMappings.getDescriptors(),
      },
```

You'll get this error -> https://github.com/manfredsteyer/module-federation-plugin-example-nx/issues/1 but just follow the instructions listed there.

Thanks to @rarmatei for the working example: https://github.com/rarmatei/module-federation-nx-libs-example

**Comment by ronaldohoch** [comment]
Thank you for the answer @smasala but i can't even build my application :/
Share the libs is a nice to have xD

**Comment by glebmachine** [comment]
@smasala as you can see in my screenshot above - there is missin AngularCompilerPlugin error.
Will provide repro soon

**Comment by ronaldohoch** [comment]
@glebmachine  stuck in this too.. :/
![image](https://user-images.githubusercontent.com/2287371/115412546-c70e4900-a1ca-11eb-9f2e-50cb18696516.png)

**Comment by smasala** [comment]
Can you shared your MF webpack config and your paths in the base tsconfig please? 

Don't forget this is also an example of sharing libs with MF: https://github.com/rarmatei/module-federation-nx-libs-example do you have any obvious differences?

Also what versions you running... what's your `ng version` output - my project is little different as I'm running webpack 4 and 5 side by side... one for storybook and one for angular (https://github.com/angular/angular-cli/issues/20571#issuecomment-823244001)

**Comment by ronaldohoch** [comment]
So, i've put my code in a public repo, see: https://github.com/ronaldohoch/angular-module-federation-building-error
This repo is a clone from https://github.com/rarmatei/module-federation-nx-libs-example, 
The error is when i try to use a lib, the project don't build or serve.


```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 11.2.8
Node: 14.15.4
OS: win32 x64

Angular: <error>
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.8 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            11.2.8 (cli-only)
@angular-devkit/schematics      11.2.8 (cli-only)
@angular/cli                    11.2.8 (cli-only)
@schematics/angular             11.2.8 (cli-only)
@schematics/update              0.1102.8 (cli-only)
ng-packagr                      <error>
rxjs                            6.6.3 (cli-only)
typescript                      <error>
```

Here is the path from tsconfig: https://github.com/ronaldohoch/angular-module-federation-building-error/blob/main/tsconfig.json

In that file: https://github.com/ronaldohoch/angular-module-federation-building-error/blob/main/projects/mfe1/src/app/flights/flights.module.ts

When i comment the lines 9 and 16, the application runs/build.

**Comment by smasala** [comment]
@ronaldohoch don't use the plugin to register shared libraries https://github.com/ronaldohoch/angular-module-federation-building-error/blob/989b0e56eb639e0990a77a47805012d5491672f7/projects/mfe1/webpack.config.js#L8. It doesn't work. The whole shared mapping thing can be removed. It doesn't work.

**Comment by ronaldohoch** [comment]
Ok, but this is from the original repo, not mine :/

https://github.com/manfredsteyer/module-federation-plugin-example/blob/main/projects/mfe1/webpack.config.js

**Comment by smasala** [comment]
@ronaldohoch you'll see in this thread that it doesn work https://github.com/manfredsteyer/module-federation-plugin-example-nx/issues/1#issuecomment-715290744

You can actually remove the entire plugin from the webpack config. It's not needed. Just add the lib under the shared section where angular is also listed. 

You'll get a tsconfig path error. Follow the thread I linked to see the plugin and steps you need to fix that error. Then it works.

**Comment by ronaldohoch** [comment]
@smasala This apparently works, but i can't build for production yet :/
But i can serve and build normaly, without the `--prod` flag

![image](https://user-images.githubusercontent.com/2287371/115714732-d4a00c00-a34d-11eb-9715-79189cf9f2c9.png)

**Comment by smasala** [comment]
You'll need to share the webpack configs, lib configs etc. Difficult to know otherwise. Can you reproduce it on your public "error" repo? It is possible, we build productively now with it.

**Comment by ronaldohoch** [comment]
Let me try, but in this case, i think it can be an NX error..: https://github.com/nrwl/nx/issues/5361

**Comment by smasala** [comment]
You need to reference the tsconfig your webpack config otherwise it can't resolve the project properly.

Read the issue I've linked above. It's in there. You need a second npm module

**Comment by ronaldohoch** [comment]
Yes, it is..:
![image](https://user-images.githubusercontent.com/2287371/115719864-e0da9800-a352-11eb-85ab-f2aa099c4435.png)

**Comment by smasala** [comment]
There's no lib under shared

**Comment by ronaldohoch** [comment]
I didn't really find where you comment about putting the lib inside the shared object.

Another thing, I found 2 possible solutions for what happened:
1st - I had 2 components inside libs/ui using the same tag "dina-tabs", I fixed that.
2nd - I was adding a scss directly to angular.json for each project, and it wasn’t working,

```json
"styles": [
   "projects/emkt-config/src/styles.scss",
   "projects/ui/src/lib/web/style/theme.scss"
 ],
```
I took it from angular.json and added it to styles.scss with @import and it's building.

But, i've made it to my two projects, one using NX and other not using NX, the project using NX still throwing the error 
```shell
> nx run emkt-config:build:production 
✔ Browser application bundle generation complete.      
ENOENT: no such file or directory, open '\package.json'
```

But, when i comment the exposes, it build '-'

**Comment by smasala** [comment]
Here it is: https://github.com/angular-architects/module-federation-plugin/issues/29#issuecomment-822756646 😊 
Difficult to tell what the problem is when I can't really see the project. Update your repo please: https://github.com/ronaldohoch/angular-module-federation-building-error

**Comment by ronaldohoch** [comment]
In the same, but other branch:
https://github.com/ronaldohoch/angular-module-federation-building-error/tree/nx-repo

**Comment by smasala** [comment]
https://github.com/ronaldohoch/angular-module-federation-building-error/blob/0e218f25bf8800017a8a36fd94338fccef496261/apps/emkt-config/webpack.config.js#L36 where is this lib registered? I don't see it in the `tsconfig.base.json`.

If I were you, I'd run the original repo to see that it works. Then gradually add your own libs and apps (or repackage existing libs) and see what it is that you have configured incorrectly.

The branch is too messy with your libs and the packages from the original example.

Start small and build up gradually.

**Comment by ronaldohoch** [comment]
And I did it anyway: s

The lib you asked:

https://github.com/ronaldohoch/angular-module-federation-building-error/blob/0e218f25bf8800017a8a36fd94338fccef496261/tsconfig.base.json#L18

**Comment by smasala** [comment]
The naming is not identical

`@dinamize/ui` and `@dina-ui`

https://github.com/ronaldohoch/angular-module-federation-building-error/blob/0e218f25bf8800017a8a36fd94338fccef496261/tsconfig.base.json#L18

https://github.com/ronaldohoch/angular-module-federation-building-error/blob/0e218f25bf8800017a8a36fd94338fccef496261/tsconfig.base.json#L18

**Comment by ronaldohoch** [comment]
Corrected, but it still gives me the same error.

![image](https://user-images.githubusercontent.com/2287371/116092967-a63b6d00-a67c-11eb-9a66-7871548aa67b.png)

**Comment by smasala** [comment]
You're going to have to run it in debug mode and see what dep. is giving you this error and reverse engineer it.

**Comment by ronaldohoch** [comment]
this is a flag?

**Comment by ronaldohoch** [comment]
Is this a flag?

**Comment by smasala** [comment]
No, if you are using vscode - you can run a JS debug terminal and catch uncaught errors

**Comment by smasala** [comment]
As for your second question in your original issue... you can also call the remotes dynamically or via the router. You'd then need to switch the urls in some way, like by using the `environment` files for example. This would be an alternative to calling them in the webpack config. 

Simplier still would be to use the `webpack.prod` config file which is also supplied and using a different URL in there.

**Comment by ronaldohoch** [comment]
Thank you!

I'll give up and don't use NX :/
Thank you for all your help!

**Comment by smasala** [comment]
You're welcome. I don't think the underlying issue in your case is NX but just a configuration or incorrect usage. After all you'll see that https://github.com/rarmatei/module-federation-nx-libs-example was made by an nx/nrwl developer and it does work.

**Comment by smasala** [comment]
@ronaldohoch just had the same issue on another project. Your fix is:
```
"@angular-devkit/build-angular": "0.1102.2",
```

**Comment by smasala** [comment]
@ronaldohoch here's the fix https://github.com/angular/angular-cli/issues/20680 - comment above seemed to just be lucky to pull the correct version. Issue is actually a webpack plugin.

**Comment by ronaldohoch** [comment]
@smasala Thank you, i'll look this asap.

**Comment by manfredsteyer** [comment]
We've solved this issue with version 12.0.0-rc.1 which works with the current Angular 12.0.0-rc.1

**Comment by smasala** [comment]
@manfredsteyer style issue is back again https://github.com/angular-architects/module-federation-plugin/issues/29#issuecomment-822278537

**Comment by NagarjunaReddyNaran** [comment]
I had the similar issue. But I found the solution.
I forgot to add **CounterModule** in my **app.module.ts** imports.  

./src/app/counter/counter.module.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: C:\Users\test\Desktop\MFE\remote-app\src\app\counter\counter.module.ts
