### ISSUE TITLE
[Bug] [Regression] [ECMAScript Module]Upgrading from version 15 to version 16

### ISSUE THREAD

**Issue by HarmoniousHarmony** [angular-architects/module-federation-plugin#350]
### Description
After updating to version 16 (both module federation library and angular), the microfront-end fails to load.

### Steps to Reproduce:

Checkout this repository: (The only difference between this repostiry and the one we have in tutorial section of angular-module-federation docs is the addition of this dependency: `"@microsoft/signalr": "^7.0.9"` )

https://github.com/HarmoniousHarmony/angular-module-federation-v16-regression

Checkout `v-15` branch, run `npm i` and in two terminals run `ng s shell` and `ng s mfe1`. You should be able to see both the sell app and the flights mfe.

Now switch to `v-16`, remove the node_modules folder and do another `npm i`, do the same steps above, and navigate to flights link by clicking on top menu link, you will see the app fails to load.

### Expected Behavior
Microfront-end app should load correctly.

### Actual Behavior:
We get this error in console and the mfe won't load

<img width="1206" alt="image" src="https://github.com/HarmoniousHarmony/angular-module-federation-v16-regression/assets/10879511/4f1418ca-de4c-4ddc-87e2-92cb093cc869">

Error text for reference:
```JavaScript
localhost/:1  Uncaught TypeError: Failed to resolve module specifier "module". Relative references must start with either "/", "./", or "../".
app.routes.ts:16  ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk node_modules_microsoft_signalr_dist_esm_index_js failed.
(missing: http://localhost:4201/node_modules_microsoft_signalr_dist_esm_index_js.js)
ChunkLoadError: Loading chunk node_modules_microsoft_signalr_dist_esm_index_js failed.
(missing: http://localhost:4201/node_modules_microsoft_signalr_dist_esm_index_js.js)
    at __webpack_require__.f.j (jsonp chunk loading:27:1)
    at ensure chunk:6:1
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (ensure chunk:5:1)
    at Object.get (sharing:45:1)
    at get (consumes:80:1)
    at getStrictSingletonVersion (consumes:50:1)
    at consumes:133:1
    at consumes:85:1
    at 2180 (consumes:138:1)
    at resolvePromise (zone.js:1251:35)
    at resolvePromise (zone.js:1205:21)
    at zone.js:1318:21
    at _ZoneDelegate.invokeTask (zone.js:446:35)
    at core.mjs:25990:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:25990:36)
    at _ZoneDelegate.invokeTask (zone.js:445:64)
    at Object.onInvokeTask (core.mjs:26300:33)
    at _ZoneDelegate.invokeTask (zone.js:445:64)
    at Zone.runTask (zone.js:211:51)
```

**Comment by JeanMeche** [comment]
FYI, this has also been reported on nx project, so this is likely related to nested dependency : https://github.com/nrwl/nx/issues/18208

**Comment by badiuoanaalexandra** [comment]
The problem seems to be related to webpack v5.86. Overriding webpack version in package.json to "5.76.1" fixes it for now. 
 
 "overrides": {
    "webpack": "5.76.1"
  }
