### ISSUE TITLE
Native Federation: exception after adding Okta npm package

### ISSUE THREAD

**Issue by pamartinez-signify** [angular-architects/module-federation-plugin#387]
After adding package:
```
    "@okta/okta-auth-js": "^7.4.3"
```

`ng serve` and `ng build` are failing with:

An unhandled exception occurred: entry.endsWith is not a function
```
[error] TypeError: entry.endsWith is not a function
    at readConfiguredSecondaries (/node_modules/@softarc/native-federation/src/lib/config/share-utils.js:146:66)
    at getSecondaries (/node_modules/@softarc/native-federation/src/lib/config/share-utils.js:113:24)
    at Object.share (/node_modules/@softarc/native-federation/src/lib/config/share-utils.js:239:33)
    at shareAll (/node_modules/@softarc/native-federation/src/lib/config/share-utils.js:190:27)
    at Object.<anonymous> (/federation.config.js:13:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
```

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. I'm going to look into it asap.

**Comment by manfredsteyer** [comment]
This works now! Please just npm i the latest version

**Comment by pamartinez-signify** [comment]
Thank you! I can now build the application.

However, I am getting the following error:
`SyntaxError: The requested module 'blob:http://localhost:4200/395ab176-349d-49ae-ba4b-aca4200bf73b' does not provide an export named 'AuthSdkError' (at _okta_okta_angular-6_3_0-dev.js:7:10)`

I am using both:
```
"@okta/okta-angular": "^6.3.0",
"@okta/okta-auth-js": "^7.4.3"
```

I noticed there is the following usage in @okta/okta-angular:
`import { AuthSdkError, toRelativeUrl } from "@okta/okta-auth-js";`
Then at some point it is used like:
`throw new AuthSdkError('...');`

For this reason the bootstrapping of the App is failing
![image](https://github.com/angular-architects/module-federation-plugin/assets/150499920/6cc0e6f5-0786-4b1f-9fce-9d9e41151567)
