### ISSUE TITLE
native-federation build after @angular-architects/native-federation 17.0.1

### ISSUE THREAD

**Issue by omishyn-dm** [angular-architects/module-federation-plugin#405]
Hi!
I changed project from module-federation config to native-federation since start angular 16 and for angular 16 it works perfectly on "@angular-architects/native-federation": "^16.0.0"! And project built in NX mono repository

Now I go to use angular 17 last version ("@angular/core": "17.0.6") with "@angular-architects/native-federation": "17.0.6". And I have a trable. This trauble is only on start build when I del cache from node_modules/.cache/native-federation (I imit start build on remote Amazone service)

INFO  Building federation artefacts
 INFO  Preparing shared npm packages
 NOTE  This only needs to be done once, as results are cached
 NOTE  Skip packages you don't want to share in your federation config
- Building...
(node:16220) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16220) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:16220) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:16220) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit

I build project on Windows 10 and node 18.18.0
Also the project build on Amazone Service and also has errors (I deleted from log path of module and amc_common_components is inner private packet)

nx run module-name:build:uat

 INFO  Building federation artefacts
 INFO  Preparing shared npm packages
 NOTE  This only needs to be done once, as results are cached
 NOTE  Skip packages you don't want to share in your federation config
- Building...

 ERR!  error linking
.../node_modules/@babel/parser/lib/index.js:356
    const error = new SyntaxError();
                  ^

SyntaxError: .../node_modules/.cache/native-federation/amc_common_components-17_5_64-dev.js: Unexpected token (54563:13)

[0m [90m 54561 |[39m                         positions[i6][33m.[39mxAdvance [33m=[39m [35m0[39m[33m;[39m[0m
[0m [90m 54562 |[39m                         positions[i6][33m.[39myAdvance [33m=[39m [35m0[39m[33m;[39m[0m
[0m[31m[1m>[22m[39m[90m 54563 |[39m              [0m
[0m [90m       |[39m              [31m[1m^[22m[39m[0m
    at toParseError [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parse-error.ts:81:19[90m)[39m
    at Parser.raise [90m.../[39mnode_modules/[4m@babel[24m/parser/src/tokenizer/index.ts:1487:19[90m)[39m
    at Parser.unexpected [90m.../[39mnode_modules/[4m@babel[24m/parser/src/tokenizer/index.ts:1528:16[90m)[39m
    at Parser.parseExprAtom [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:1349:16[90m)[39m
    at Parser.parseExprSubscripts [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:705:23[90m)[39m
    at Parser.parseUpdate [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:682:21[90m)[39m
    at Parser.parseMaybeUnary [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:644:23[90m)[39m
    at Parser.parseMaybeUnaryOrPrivate [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:382:14[90m)[39m
    at Parser.parseExprOps [90m.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:394:23[90m)[39m
    at Parser.parseMaybeConditional [90m.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:349:23[90m)[39m
    at Parser.parseMaybeAssign [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:289:21[90m)[39m
    at Parser.parseExpressionBase [90m.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:212:23[90m)[39m
    at callback [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:203:39[90m)[39m
    at Parser.allowInAnd [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:3134:16[90m)[39m
    at Parser.parseExpression [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:203:17[90m)[39m
    at Parser.parseStatementContent [90m.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:644:23[90m)[39m
    at Parser.parseStatementLike [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:416:17[90m)[39m
    at Parser.parseStatementListItem [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:365:17[90m)[39m
    at Parser.parseBlockOrModuleBlockBody [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:1394:16[90m)[39m
    at Parser.parseBlockBody [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:1367:10[90m)[39m
    at Parser.parseBlock [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:1335:10[90m)[39m
    at Parser.parseStatementContent [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:563:21[90m)[39m
    at Parser.parseStatementLike [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:416:17[90m)[39m
    at Parser.parseStatementOrSloppyAnnexBFunctionDeclaration [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:385:17[90m)[39m
    at Parser.parseIfStatement [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:1045:28[90m)[39m
    at Parser.parseStatementContent [90m.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:475:21[90m)[39m
    at Parser.parseStatementLike [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:416:17[90m)[39m
    at Parser.parseStatementListItem [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:365:17[90m)[39m
    at Parser.parseBlockOrModuleBlockBody [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:1394:16[90m)[39m
    at Parser.parseBlockBody [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:1367:10[90m)[39m
    at Parser.parseBlock [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:1335:10[90m)[39m
    at Parser.parseStatementContent [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:563:21[90m)[39m
    at Parser.parseStatementLike [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:416:17[90m)[39m
    at Parser.parseStatement [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:396:17[90m)[39m
    at callback [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:1450:14[90m)[39m
    at Parser.withSmartMixTopicForbiddingContext [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:3113:14[90m)[39m
    at Parser.parseFor [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:1448:12[90m)[39m
    at Parser.parseForStatement [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:973:21[90m)[39m
    at Parser.parseStatementContent [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:446:21[90m)[39m
    at Parser.parseStatementLike [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:416:17[90m)[39m
    at Parser.parseStatementListItem [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:365:17[90m)[39m
    at Parser.parseBlockOrModuleBlockBody [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:1394:16[90m)[39m
    at Parser.parseBlockBody [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:1367:10[90m)[39m
    at Parser.parseBlock [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:1335:10[90m)[39m
    at Parser.parseFunctionBody [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:2586:24[90m)[39m
    at Parser.parseFunctionBodyAndFinish [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:2555:10[90m)[39m
    at callback [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:1632:12[90m)[39m
    at Parser.withSmartMixTopicForbiddingContext [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:3113:14[90m)[39m
    at Parser.parseFunction [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/statement.ts:1630:10[90m)[39m
    at Parser.parseFunctionOrFunctionSent [90m(.../[39mnode_modules/[4m@babel[24m/parser/src/parser/expression.ts:1624:17[90m)[39m {
  code: [32m'BABEL_PARSE_ERROR'[39m,
  reasonCode: [32m'UnexpectedToken'[39m,
  loc: Position { line: [33m54563[39m, column: [33m13[39m, index: [33m2764793[39m },
  pos: [33m2764793[39m
}

Node.js v18.18.0 

When I reduced version of @angular-architects/native-federation to 17.0.1 I can build. Yes, I have a problem with index.html, but it works. I check all next versions: 17.0.2, 17.0.3 and 17.0.6. 17.0.2 doesn't work absolutly, 17.0.3 - 17.0.6 have the same errors

**Comment by manfredsteyer** [comment]
Thanks for pointing this out.

Can you pls provide a reproduction?

**Comment by omishyn-dm** [comment]
Hello, I found problem in ora dependance
I added to index.js next

require('events').EventEmitter.defaultMaxListeners = 15;

and it resolved warnings
