### ISSUE TITLE
Javascript error when loading the remote entry upfront

### ISSUE THREAD

**Issue by eironman** [angular-architects/module-federation-plugin#41]
Hello, 
    I am trying to improve the library sharing between shell and microfronts using the feature to load the remote entry upfront:

    https://www.angulararchitects.io/aktuelles/dynamic-module-federation-with-angular/ -> Improvement for Dynamic Module Federation

   I am attaching screenshots of the code and the error:

   zone-evergreen.js:1063 Unhandled Promise rejection: Cannot read property 'init' of undefined ; Zone: <root> ; Task: HTMLScriptElement.addEventListener:load ; Value: TypeError: Cannot read property 'init' of undefined
    at dynamic-federation.js:28
    at Generator.next (<anonymous>)
    at tslib.es6.js:74
    at new ZoneAwarePromise (zone-evergreen.js:1387)
    at Module.__awaiter (tslib.es6.js:70)
    at initRemote (dynamic-federation.js:17)
    at HTMLScriptElement.script.onload [as __zone_symbol__ON_PROPERTYload] (dynamic-federation.js:44)
    at HTMLScriptElement.wrapFn (zone-evergreen.js:763)
    at ZoneDelegate.invokeTask (zone-evergreen.js:406)
    at Zone.runTask (zone-evergreen.js:178) TypeError: Cannot read property 'init' of undefined
    at http://localhost:3000/vendor.js:52:25
    at Generator.next (<anonymous>)
    at http://localhost:3000/vendor.js:195:71
    at new ZoneAwarePromise (http://localhost:3000/polyfills.js:1397:29)
    at Module.__awaiter (http://localhost:3000/vendor.js:191:12)
    at initRemote (http://localhost:3000/vendor.js:41:20)
    at HTMLScriptElement.script.onload [as __zone_symbol__ON_PROPERTYload] (http://localhost:3000/vendor.js:68:13)
    at HTMLScriptElement.wrapFn (http://localhost:3000/polyfills.js:773:39)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:416:31)
    at Zone.runTask (http://localhost:3000/polyfills.js:188:47)

![Captura de pantalla de 2021-05-07 09-26-49](https://user-images.githubusercontent.com/1751920/117414618-a1e24000-af17-11eb-8d83-c56064247e8c.png)
![Captura de pantalla de 2021-05-07 09-35-26](https://user-images.githubusercontent.com/1751920/117414626-a4449a00-af17-11eb-81e1-b35a1b0de331.png)

**Comment by eironman** [comment]
Sure! I'll create a project in github and I'll share it.

**Comment by eironman** [comment]
Here you have three repos with the shell and two apps loaded by the shell.
The shell is giving the error I referred in this issue, just return main.ts to its original content to see it working.
Hope this helps, and many thanks for all the work you are doing!

https://github.com/eironman/module-federation-shell
https://github.com/eironman/module-federation-app-a
https://github.com/eironman/module-federation-app-b

**Comment by eironman** [comment]
@manfredsteyer, could you take a look at it? No hurries!

**Comment by manfredsteyer** [comment]
Thanks for the reminder. Look into it asap

**Comment by GillianPerard** [comment]
Hi, I think the problem is inside your shell app `main.ts`.
You use in the  `loadRemoteEntry` function the names with dashes whereas you use underscores in the micro-frontends application names.

Use `app_a`  instead of  `app-a`.
Use `app_b`  instead of  `app-b`.

**Comment by eironman** [comment]
Oh! @GillianPerard, I see your answer now! Sorry, and thanks for it.
