### ISSUE TITLE
NF and NX, failing to resolve import of libraries

### ISSUE THREAD

**Issue by Frank-Troia** [angular-architects/module-federation-plugin#449]
I'm trying to migrate my NX project to utilize native federation and I'm struggling to get the library imports to work.

Here is the error I'm getting when serving one of the microfrontends

```
 INFO  Building federation artefacts

Initial Chunk Files      | Names         |  Raw Size
styles.css               | styles        | 195.17 kB | 
polyfills.js             | polyfills     | 178.81 kB | 
main.js                  | main          | 292 bytes | 

                         | Initial Total | 374.26 kB

Lazy Chunk Files         | Names         |  Raw Size
bootstrap-PZCGXKON.js    | bootstrap     |   2.60 kB | 
entry.module-NE57NXWG.js | entry-module  |   1.96 kB | 

Application bundle generation complete. [4.844 seconds]
Watch mode enabled. Watching for file changes...
Failed to resolve dependency: @xyz/branding-main, present in 'optimizeDeps.include'
Failed to resolve dependency: @xyz/branding/feature-brander, present in 'optimizeDeps.include'
Failed to resolve dependency: @xyz/shared/util-branding-config, present in 'optimizeDeps.include'
Failed to resolve dependency: @xyz/shared/util-translation-config, present in 'optimizeDeps.include'
  ➜  Local:   http://localhost:4203/
9:09:52 AM [vite] Internal server error: Failed to resolve import "@xyz/shared/util-branding-config" from ".angular/vite-root/branding/bootstrap-PZCGXKON.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/vagrant/dev/hub-frontend/.angular/vite-root/branding/bootstrap-PZCGXKON.js:1:47
  4  |  
  5  |  // apps/branding/src/app/app.module.ts
  6  |  import { SharedUtilBrandingConfigModule } from "@xyz/shared/util-branding-config";
     |                                                  ^
  7  |  import { SharedUtilTranslationConfigModule } from "@xyz/shared/util-translation-config";
  8  |  import { BrowserAnimationsModule } from "@angular/platform-browser/animations";
      at formatError (file:///home/vagrant/dev/hub-frontend/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44062:46)
      at TransformContext.error (file:///home/vagrant/dev/hub-frontend/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44058:19)
      at normalizeUrl (file:///home/vagrant/dev/hub-frontend/node_modules/vite/dist/node/chunks/dep-68d1a114.js:41844:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///home/vagrant/dev/hub-frontend/node_modules/vite/dist/node/chunks/dep-68d1a114.js:41998:47
      at async Promise.all (index 2)
      at async TransformContext.transform (file:///home/vagrant/dev/hub-frontend/node_modules/vite/dist/node/chunks/dep-68d1a114.js:41914:13)
      at async Object.transform (file:///home/vagrant/dev/hub-frontend/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44352:30)
      at async loadAndTransform (file:///home/vagrant/dev/hub-frontend/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55026:29)
      at async viteTransformMiddleware (file:///home/vagrant/dev/hub-frontend/node_modules/vite/dist/node/chunks/dep-68d1a114.js:64430:32)

```

I'm not exactly sure where to look to resolve this, but here are the contents of some of the files that I think matter:

federation.config.ts
```
const {
  withNativeFederation,
  shareAll,
} = require('@angular-architects/native-federation/config');

module.exports = withNativeFederation({
  name: 'branding',

  exposes: {
    './Component': './apps/branding/src/app/app.component.ts',
    './Module': './apps/branding/src/app/app.module.ts',
  },

  shared: {
    ...shareAll({
      singleton: true,
      strictVersion: true,
      requiredVersion: 'auto',
    }),
  },

  skip: [
    'rxjs/ajax',
    'rxjs/fetch',
    'rxjs/testing',
    'rxjs/webSocket',
    // Add further packages you don't need at runtime
  ],
});
```

tsconfig.base.json
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "ES2022",
    "module": "ES2022",
    "lib": ["ES2022", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@xyz/branding-main": ["libs/branding/main/src/index.ts"],
      "@xyz/branding/feature-brander": [
        "libs/branding/feature-brander/src/index.ts"
      ],
      "@xyz/shared/util-branding-config": [
        "libs/shared/util-branding-config/src/index.ts"
      ],
      "@xyz/shared/util-translation-config": [
        "libs/shared/util-translation-config/src/index.ts"
      ]
    }
  },
  "exclude": ["node_modules", "tmp"]
}

```

I'm using version 17.1.0 of the native federation library.

Any help would be appreciated!

**Comment by Frank-Troia** [comment]
I think the issue was that I was using angular v17.0.x. Once I upgraded to v17.1.1 it worked!
