### ISSUE TITLE
ngDevMode is not defined

### ISSUE THREAD

**Issue by DavidGoethCplace** [angular-architects/module-federation-plugin#458]
Hi,

When using the `ModuleFederationPlugin` within a custom webpack 5 configuration that is set to 'development' mode, I face the problem that angular produces a 'ReferenceError: ngDevMode is not defined' error.

I have a simple solution by defining the ngDevMode manually:

```javascript
config.plugins.push(
new webpack.DefinePlugin({
      ngDevMode: config.mode === 'development'
}));
```

But I think that should be handled by `ModuleFederationPlugin` directly. 

Greetings
David

**Comment by raulmelo** [comment]
I have the same problem, I can't run MFE because of ngDevMode

**Comment by raulmelo** [comment]
solution: webpack.config.js
```
const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const mf = require("@angular-architects/module-federation/webpack");
const webpack = require("webpack");
const path = require("path");
const share = mf.share;

const sharedMappings = new mf.SharedMappings();
sharedMappings.register(
  path.join(__dirname, '../../tsconfig.json'),
  [/* mapped paths to share */]);

module.exports = {
....OTHERS,
  plugins: [

   // DISABLE ngDevMode as it is not needed in a remoteEntry
    new webpack.DefinePlugin({
      ngDevMode: "undefined",
    }),
    // END DISABLE ngDevMode as it is not needed in a remoteEntry

    new ModuleFederationPlugin({
      library: { type: "module" },
      name: "NAME",
      filename: "remoteEntry.js",
      exposes: {
        "./web-components": "./projects/NAME/src/bootstrap.ts",
      },
      ...
    }),
  ],
};

**Comment by Teifun2** [comment]
Im running into the same issue.

For me it is caused by @angular/forms

```
providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => CheckboxComponent),
      multi: true,
    },
],
```

the NG_VALUE_ACCESSOR is causing this issue:
https://github.com/angular/angular/blob/main/packages/forms/src/directives/control_value_accessor.ts#L212

**Comment by Teifun2** [comment]
Probably this is due to the missing initalization. https://github.com/angular/angular/blob/main/packages/core/src/util/ng_dev_mode.ts#L119

However this does not explain why the NgDevMode is missing with ModuleFederation

**Comment by dbeachy1** [comment]
@raulmelo Thanks for the workaround info. When I do that in my webpack.config.js, the compilation blows up with:

```
Generating browser application bundles (phase: setup).../Users/dobeachy/ise/frontend/node_modules/webpack/lib/DefinePlugin.js:341
		compiler.hooks.compilation.tap(
		                           ^

TypeError: Cannot read properties of undefined (reading 'tap')
    at DefinePlugin.apply (/Users/dobeachy/ise/frontend/node_modules/webpack/lib/DefinePlugin.js:341:30)
    at exports.createResolver (/Users/dobeachy/ise/frontend/node_modules/enhanced-resolve/lib/ResolverFactory.js:695:11)
    at ResolverFactory._create (/Users/dobeachy/ise/frontend/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/ResolverFactory.js:131:12)
    at ResolverFactory.get (/Users/dobeachy/ise/frontend/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/ResolverFactory.js:112:28)
    at exports.resolveMatchedConfigs (/Users/dobeachy/ise/frontend/node_modules/webpack/lib/sharing/resolveMatchedConfigs.js:46:47)
    at /Users/dobeachy/ise/frontend/node_modules/webpack/lib/sharing/ConsumeSharedPlugin.js:126:21
    at Hook.eval [as call] (eval at create (/Users/dobeachy/ise/frontend/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:84:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/dobeachy/ise/frontend/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/dobeachy/ise/frontend/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1125:30)
    at /Users/dobeachy/ise/frontend/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1170:29
```
My `webpack.config.js` has:

```
, plugins: [
      new webpack.DefinePlugin({
        // DISABLE ngDevMode as it is not needed in a remoteEntry
        ngDevMode: 'undefined'
      }),

```

I'm using `"@angular-architects/module-federation": "^17.0.8",`, but I also tried it with 17.0.1 and I'm getting the same error. Any ideas, anyone?

**Comment by raulmelo** [comment]
@dbeachy1 share your webpack.config.js please. 

 my code shell MFE with angular

```
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');
const mf = require('@angular-architects/module-federation/webpack');
const webpack = require('webpack'); 
const path = require('path');
const share = mf.share;


const sharedMappings = new mf.SharedMappings();
sharedMappings.register(path.join(__dirname, './tsconfig.json'), [
  /* mapped paths to share */
]);


module.exports = {
  output: {
    uniqueName: 'modulo-core',
    publicPath: 'auto',
  },
  optimization: {
    runtimeChunk: false,
  },
  resolve: {
    alias: {
      ...sharedMappings.getAliases(),
    },
  },
  experiments: {
    outputModule: true,
  },
  plugins: [
    // DISABLE ngDevMode as it is not needed in a remoteEntry
    new webpack.DefinePlugin({
      ngDevMode: 'undefined',
    }),
    // END DISABLE ngDevMode as it is not needed in a remoteEntry
    new ModuleFederationPlugin({
      library: { type: 'module' },
      shared: share({
        '@angular/core': { requiredVersion: 'auto' },
        '@angular/common': { requiredVersion: 'auto' },
        '@angular/router': { requiredVersion: 'auto' },
        '@angular/common/http': { requiredVersion: 'auto' },
        rxjs: { requiredVersion: 'auto' },
        ...sharedMappings.getDescriptors(),
      }),
    }),
    sharedMappings.getPlugin(),
  ],
};

```

**Comment by dbeachy1** [comment]
@raulmelo Thanks for info. Unfortunately I can't share my entire `webpack.config.js` because the code is private (the place I work), but the relevant part of my `webpack.config.js` is what I posted above. Here are the relevant dependencies, though:

```
    "@angular-architects/module-federation": "^17.0.8",
    "@angular/animations": "17.1.3",
    "@angular/cdk": "17.1.2",
    "@angular/common": "17.1.3",
    "@angular/compiler": "17.1.3",
    "@angular/core": "17.1.3",
    "@angular/forms": "17.1.3",
    "@angular/localize": "17.1.3",
    "@angular/platform-browser": "17.1.3",
    "@angular/platform-browser-dynamic": "17.1.3",
    "@angular/router": "17.1.3",
```

So I'm using a slightly newer version of Angular (17.1.3 vs. your 17.1.1), and a slightly newer module-federation (17.0.8 vs. your 17.0.1). I also tried setting a JavaScript global variable named `ngDevMode` in the MFE's `index.js`, but that doesn't fix the runtime bug, either. I'm debating whether to just switch to an older version of Angular 17 from before this breaking change in January...

**Comment by dbeachy1** [comment]
@raulmelo I have it working now, thanks for posting your code shell MFE! It turns out I was putting the `new webpack.DefinePlugin` block in the wrong `plugins` section in my `webpack.config.js` (we have some `resolve` plugins as well).  Thanks again!

**Comment by scottfwalter** [comment]
For me it seems to be an issue when swapping out MFE child apps.  If the first child app was built with dev mode then it's not a problem.  However, if first load a production mode app and then switch to a dev mode app, I see the issue.

Before switching from the production mode child to the dev mode child I enter this into the console:  window.ngDevMode = {} then I don't see the problem.

It seems like Angular is not properly resetting dev mode when switching out child apps.

**Comment by gsgonzalez88** [comment]
thanks @raulmelo 

    // DISABLE ngDevMode as it is not needed in a remoteEntry
    new webpack.DefinePlugin({
      ngDevMode: 'undefined',
    }),
    // END DISABLE ngDevMode as it is not needed in a remoteEntry
    
    this solved my problem!

**Comment by oussama-benmahmoud** [comment]
I encountered the same issue. Initially, I followed what @raulmelo suggested, which resolved it. However, I later removed that fix because other MFEs were working fine without the additional code.

Eventually, I realized that the issue was due to a missing dependency in the shared object: @angular/platform-browser. Once I added it, everything started working correctly.

```
new ModuleFederationPlugin({
      library: { type: 'module' },
      shared: share({
        '@angular/core': { requiredVersion: 'auto' },
        '@angular/common': { requiredVersion: 'auto' },
        '@angular/router': { requiredVersion: 'auto' },
        '@angular/common/http': { requiredVersion: 'auto' },
        '@angular/platform-browser': { requiredVersion: 'auto' },
        rxjs: { requiredVersion: 'auto' },
        ...sharedMappings.getDescriptors(),
      }),
```
