### ISSUE TITLE
NullInjectorError when loading Angular 17.1 remote (webcomponent wrapper) into Angular 17.0 shell

### ISSUE THREAD

**Issue by TimmermanDave** [angular-architects/module-federation-plugin#461]
I get a NullInjectorError when loading an Angular 17.1 remote (webcomponent wrapped) into my Angular 17.0 shell.
I also load an Angular 16.2 remote without issue (same setup), so I know it works

## Error

```
NullInjectorError: R3InjectorError(Environment Injector)[ComponentFactoryResolver$1 -> ComponentFactoryResolver$1]: 
  NullInjectorError: No provider for ComponentFactoryResolver$1!
    at NullInjector.get (_angular_core-17_1_2-dev.js:3204:21)
    at R3Injector.get (_angular_core-17_1_2-dev.js:3509:27)
    at R3Injector.get (_angular_core-17_1_2-dev.js:3509:27)
    at getComponentInputs (_angular_elements-17_1_2-dev.js:65:45)
    at createCustomElement (_angular_elements-17_1_2-dev.js:317:18)
    at Object.<anonymous> (bootstrap.ts:17:15)
    at Generator.next (<anonymous>)
    at fulfilled (Component.js:12:24)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at _Zone.run (zone.js:129:43)
```
    
## Setup remote (mfe2) (Angular 17.1)

**bootstrap.ts**
```
import { environment } from './environments/environment';
import { enableProdMode } from '@angular/core';
import { createApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';
import { createCustomElement } from '@angular/elements';

if (environment.production) {
  enableProdMode();
}

(async () => {
  debugger
  const app = await createApplication({
    providers: [],
  });
  const elm = createCustomElement(AppComponent, {
    injector: app.injector, // THIS THROWS THE ERROR
  });
  customElements.define('mfe2-root', elm);
})();
``` 
**federation.config.js**
```
const { withNativeFederation, shareAll, share } = require('@angular-architects/native-federation/config');

module.exports = withNativeFederation({
  name: 'mfe2',
  exposes: {
    './Component': './projects/mfe2/src/bootstrap.ts', // <-- packaged remotes need to reference the bootrap file
  },
  shared: {
    ...shareAll({ singleton: true, strictVersion: true, requiredVersion: "auto" }),
  },
  skip: [
    'rxjs/ajax',
    'rxjs/fetch',
    'rxjs/testing',
    'rxjs/webSocket',
    // Add further packages you don't need at runtime
  ]
});
```

## Setup shell (Angular 17.0)

**app.routes.ts**
```
import { Routes } from '@angular/router';
import { loadRemoteModule } from '@angular-architects/native-federation';
import { HomeComponent } from './home/home.component';
import { NotFoundComponent } from './not-found/not-found.component';
import { Mfe2WrapperComponent } from './mfe2-wrapper/mfe2.component';
import { Mfe3WrapperComponent } from './mfe3-wrapper/mfe3.component';

export const APP_ROUTES: Routes = [
  {
    path: '',
    component: HomeComponent,
    pathMatch: 'full',
  },
  {
    path: 'mfe1', // <-- integrated app (same repo as the shell, no issues, also no webcomponent wrapper needed)
    loadComponent: () =>
      loadRemoteModule('mfe1', './Component').then((m) => m.AppComponent),
  },
  {
    path: 'mfe2', // <-- remote app (NullInjectorError, webcomponent wrapper needed, newer MINOR version of Angular)
    component: Mfe2WrapperComponent,
  },
  {
    path: 'mfe3', // <-- remote app (No issues, webcomponent wrapper needed, older MAJOR version of Angular)
    component: Mfe3WrapperComponent,
  },
  {
    path: '**',
    component: NotFoundComponent,
  },
  // DO NOT insert routes after this one.
  // { path:'**', ...} needs to be the LAST one.
];
```
**mfe2.component.ts**
```
import { loadRemoteModule } from "@angular-architects/native-federation";
import { CommonModule } from "@angular/common";
import { Component, ElementRef, OnInit, inject } from "@angular/core";

@Component({
  selector: 'app-mfe2-component',
  standalone: true,
  imports: [CommonModule],
  template: '',
})
export class Mfe2WrapperComponent implements OnInit {
  elm = inject(ElementRef);

  async ngOnInit() {
    await loadRemoteModule('mfe2', './Component');
    const root = document.createElement('mfe2-root');
    this.elm.nativeElement.appendChild(root);
  }
}
```

**Comment by manfredsteyer** [comment]
If you want to mix and match different Angular Versions, you need to wrap the applications up into web components.

Please see here:
https://www.angulararchitects.io/blog/micro-frontends-with-modern-angular-part-2-multi-version-and-multi-framework-solutions-with-angular-elements-and-web-components/

**Comment by TimmermanDave** [comment]
i did:

path: 'mfe2', // <-- remote app (NullInjectorError, webcomponent wrapper needed, newer MINOR version of Angular)
component: Mfe2WrapperComponent,
    
and:

export class Mfe2WrapperComponent implements OnInit {
  elm = inject(ElementRef);

  async ngOnInit() {
    await loadRemoteModule('mfe2', './Component');
    const root = document.createElement('mfe2-root');
    this.elm.nativeElement.appendChild(root);
  }
}

Point is that with angular 16.2 it works (in a shell with anhular 17.0)
But with a remote running on 17.1 it doesnt
