### ISSUE TITLE
Migration from 17.0.7 to 17.1.6 triggers NG0203

### ISSUE THREAD

**Issue by ybubelo** [angular-architects/module-federation-plugin#467]
Steps to reproduce:

1. Download and unzip the attached native-federation-17.1.6.zip
2. Run npm install in both shell and remote
3. Run remote and shell with ng serve
4. Navigate to http://localhost:4200/ (shell) and click "remote"
5. Observe the error
`ERROR Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203

    at injectInjectorOnly (_angular_core-17_0_8-dev.js:512:11)
    at ɵɵinject (_angular_core-17_0_8-dev.js:522:59)
    at Object.factory (_angular_core-17_0_8-dev.js:15015:45)
    at core.mjs:6189:43
    at runInInjectorProfilerContext (core.mjs:867:9)
    at R3Injector.hydrate (core.mjs:6188:17)
    at R3Injector.get (core.mjs:6058:33)
    at definition.getStandaloneInjector (_angular_core-17_0_8-dev.js:15022:27)
    at ComponentFactory.create (core.mjs:15428:57)
    at ViewContainerRef2.createComponent (core.mjs:20019:47)`

Expected behavior:
Component from remote module is displayed without errors.
See attached native-federation-17.0.7.zip for the version of code before upgrade.

[native-federation-17.0.7.zip](https://github.com/angular-architects/module-federation-plugin/files/14268609/native-federation-17.0.7.zip)
[native-federation-17.1.6.zip](https://github.com/angular-architects/module-federation-plugin/files/14268611/native-federation-17.1.6.zip)

**Comment by ybubelo** [comment]
Upgrading Angular to 17.1.3 fixes the issue.
