### ISSUE TITLE
dev-server reloadShell "server is not started"

### ISSUE THREAD

**Issue by mattiaslvv** [angular-architects/module-federation-plugin#652]
I have a minimal application for trying out Native Federation, using angular 18 with esbuild and Native federation 18.2.2, Node 20.17.0
Using executors @angular-architects/native-federation:build for serving, works fine and I can get the shell to load the remote app. However, when making a change in either the shell or the microfrontend and trigger a reload I get the following error, stopping the serve:

`WORKROOT\node_modules\@angular-architects\native-federation\src\utils\dev-server.js:60
        throw new Error('server is not started');
        ^
Error: server is not started
    at reloadShell (WORKROOT\node_modules\@angular-architects\native-federation\src\utils\dev-server.js:60:15
    at Timeout._onTimeout (WORKROOT\node_modules\@angular-architects\native-federation\src\builders\build\builder.js:208:75
    at listOnTimeout (node:internal/timers:569:17
    at process.processTimers (node:internal/timers:512:7)
`
running both shell and microfrontend with command:
`nx run PROJECTNAME:serve`

the configuration for "serve" taken from examples online (in this case for the remote-app, shell is on different port):
`
    "serve": {
      "executor": "@angular-architects/native-federation:build",
      "options": {
        "target": "remote-app:serve-original:development",
        "rebuildDelay": 0,
        "dev": true,
        "port": 4200
      }
    },
`
Is there any specific configuration that I am missing for this to work?

**Comment by mattiaslvv** [comment]
the issue seems to be resolved once removing "port" field from the "serve" config. Closing.
